"""
Переносит данные бэкенда в index.html: координаты адресов, депо и коэффициенты извилистости.

Запуск (сеть не нужна):  python3 embed_frontend_assets.py

Фронтенд умеет работать автономно, из file://, где бэкенда нет вообще. Чтобы в этом
режиме он не считал координаты по собственному алгоритму (раньше они расходились с
Python на 0.4-2 км), таблицы вшиваются в размеченный блок AUTOGENERATED внутри index.html.

Запускать после geocode_addresses.py и build_osrm_cache.py — тогда во фронтенд
попадут актуальные координаты и коэффициенты, откалиброванные по графу.
"""
from __future__ import annotations

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

import vrptw_4pass_solver as solver  # noqa: E402

HTML = os.path.join(ROOT, "index.html")
BEGIN = "/* ==== AUTOGENERATED"
END = "/* ==== END AUTOGENERATED ==== */"


def js_literal(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def build_block() -> str:
    factors = solver.calibrate_winding_factors() or dict(solver.WINDING_FACTORS)
    for mode in solver.WINDING_FACTORS:
        factors.setdefault(mode, solver.WINDING_FACTORS[mode])

    depots = []
    for dep_id, cfg in solver.DEPOTS.items():
        coords, display, source = solver.resolve_depot(cfg["keys"][0] if cfg["keys"] else "", "")
        if dep_id != "vostok" and cfg["keys"]:
            coords, display, source = solver.resolve_depot(cfg["keys"][0], "")
        depots.append({
            "id": dep_id,
            "coords": [round(coords[0], 6), round(coords[1], 6)],
            "display": display,
            "source": source,
            "keys": cfg["keys"],
        })
    # порядок важен: "восток" — это запасной вариант, он должен проверяться последним
    depots.sort(key=lambda d: (d["id"] == "vostok", d["id"]))

    lines = [
        "    /* ==== AUTOGENERATED: не править руками, перегенерируется embed_frontend_assets.py ====",
        "       Координаты адресов, депо и коэффициенты извилистости приходят с бэкенда",
        "       (geocode_cache.json / .osrm_cache.json). Раньше фронтенд считал их сам",
        "       по другому алгоритму и расходился с Python на сотни метров. */",
        f"    const GEOCODE_CACHE = {js_literal(solver._GEOCODE_CACHE)};",
        "    const DEPOTS = [",
    ]
    for d in depots:
        lines.append(
            f"      {{ id: {js_literal(d['id'])}, coords: {js_literal(d['coords'])}, "
            f"display: {js_literal(d['display'])},"
        )
        lines.append(f"        keys: {js_literal(d['keys'])} }},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("    ];")
    lines.append(f"    const WINDING_FACTORS = {js_literal(factors)};")
    lines.append("    /* ==== END AUTOGENERATED ==== */")
    return "\n".join(lines)


def main() -> int:
    html = open(HTML, encoding="utf-8").read()
    start = html.find(BEGIN)
    end = html.find(END)
    if start == -1 or end == -1:
        print("В index.html не найден блок AUTOGENERATED — нечего обновлять.")
        return 1

    line_start = html.rfind("\n", 0, start) + 1
    new_html = html[:line_start] + build_block() + html[end + len(END):]
    open(HTML, "w", encoding="utf-8").write(new_html)

    geo_total = len(solver._GEOCODE_CACHE)
    depots_osm = sum(
        1 for cfg in solver.DEPOTS.values()
        if solver.resolve_depot(cfg["keys"][0] if cfg["keys"] else "", "")[2] == "osm"
    )
    print(f"index.html обновлён:")
    print(f"  адресов в GEOCODE_CACHE: {geo_total}")
    print(f"  депо с реальными координатами: {depots_osm}/3")
    print(f"  коэффициенты извилистости: {solver.calibrate_winding_factors() or solver.WINDING_FACTORS}")
    if geo_total == 0:
        print("  ВНИМАНИЕ: geocode_cache.json пуст — сначала запустите geocode_addresses.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
